[package]
name = "scog"
description = "Sync Config Over Git"
version = "0.1.0"
authors = ["Davide Bizzarri <davide@bizzarri.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"
chrono = "0.4"
serde_yaml = "0.7"
git2 = "0.7"